apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs-app
  template:
    metadata:
      labels:
        app: nestjs-app
    spec:
      containers:
        - name: app                # збігається з K8S_CONTAINER=app у CI
          image: nginx:alpine      # CI замінить на образ з ECR через `set image`
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: app-secrets
          # бажано, щоб REDIS_HOST був = "redis" (ім'я сервісу)
          env:
            - name: REDIS_HOST
              value: redis
