apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis                  # Ім’я Deployment для Redis
  namespace: nestjs-app        # Namespace, де запускається Redis (має збігатися з namespace для додатка)
spec:
  replicas: 1                  # Одна репліка (якщо хочеш HA, роблять StatefulSet з декількома)
  selector:
    matchLabels:
      app: redis               # Лейбл, за яким Service знайде цей Pod
  template:
    metadata:
      labels:
        app: redis              # Лейбл для селектора
    spec:
      containers:
        - name: redis
          image: redis:7-alpine # Легкий офіційний образ Redis
          ports:
            - containerPort: 6379 # Стандартний порт Redis
          command:               # Запускаємо Redis із параметром для пароля
            - "redis-server"
            - "--requirepass"
            - "$(REDIS_PASSWORD)" # Використовуємо змінну середовища
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret   # Назва секрету з паролем
                  key: redis-password # Ключ у секреті, де збережений пароль
