name: CI-CD
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

concurrency:
  group: ci-cd-${{ github.ref }}
  cancel-in-progress: true

env:
  K8S_DEPLOYMENT: nestjs-app
  K8S_CONTAINER: app

jobs:
  build-push:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_URI: ${{ steps.meta.outputs.image_uri }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (static keys)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Who am I
        run: aws sts get-caller-identity

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          use: true
          install: true
          driver-opts: |
            image=moby/buildkit:latest
            network=host

      - name: Set image tag
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:${{ steps.vars.outputs.TAG }}
            ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:latest
          # кеш тимчасово вимкнений
          # cache-from: type=gha
          # cache-to: type=gha,mode=max

      - name: Export image URI
        id: meta
        run: echo "image_uri=${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:${{ steps.vars.outputs.TAG }}" >> $GITHUB_OUTPUT

  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (static keys)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Who am I
        run: aws sts get-caller-identity

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.30.0'

      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --name "${{ secrets.EKS_CLUSTER }}" --region "${{ secrets.AWS_REGION }}"

      # == НОРМАЛІЗУЄМО NAMESPACE І ВИКОРИСТОВУЄМО ДАЛІ ТІЛЬКИ ЙОГО ==
      - name: Normalize namespace
        id: ns
        run: |
          NS="$(printf "%s" "${{ secrets.K8S_NAMESPACE }}" | tr -d '\r' | tr -d '\n' | xargs)"
          echo "NS=$NS"
          echo "NS=$NS" >> $GITHUB_OUTPUT

      - name: Ensure namespace exists
        run: |
          kubectl get ns "${{ steps.ns.outputs.NS }}" >/dev/null 2>&1 || \
          kubectl create ns "${{ steps.ns.outputs.NS }}"

      - name: Create/Update app secrets from ENV_FILE
        run: |
          cat > .env <<'EOF'
          ${{ secrets.ENV_FILE }}
          EOF
          # обидві команди -n "$NS"
          kubectl -n "${{ steps.ns.outputs.NS }}" create secret generic app-secrets \
            --from-env-file=.env --dry-run=client -o yaml | \
          kubectl -n "${{ steps.ns.outputs.NS }}" apply -f -

      - name: Apply manifests
        run: |
          kubectl -n "${{ steps.ns.outputs.NS }}" apply -f k8s/deployment-redis.yaml -f k8s/service-redis.yaml
          kubectl -n "${{ steps.ns.outputs.NS }}" apply -f k8s/deployment-app.yaml -f k8s/service-app.yaml
          # опційно:
          # kubectl -n "${{ steps.ns.outputs.NS }}" apply -f k8s/ingress.yaml -f k8s/hpa.yaml -f k8s/networkpolicy.yaml

      - name: Set new image and rollout
        run: |
          kubectl -n "${{ steps.ns.outputs.NS }}" set image deployment/${{ env.K8S_DEPLOYMENT }} ${{ env.K8S_CONTAINER }}="${{ needs.build-push.outputs.IMAGE_URI }}"
          kubectl -n "${{ steps.ns.outputs.NS }}" rollout status deployment/${{ env.K8S_DEPLOYMENT }} --timeout=180s

      - name: Debug (if needed)
        if: failure()
        run: |
          kubectl -n "${{ steps.ns.outputs.NS }}" get pods -o wide || true
          kubectl -n "${{ steps.ns.outputs.NS }}" describe deploy/${{ env.K8S_DEPLOYMENT }} || true
          kubectl -n "${{ steps.ns.outputs.NS }}" logs deploy/${{ env.K8S_DEPLOYMENT }} --tail=200 || true
          kubectl -n "${{ steps.ns.outputs.NS }}" get events --sort-by=.lastTimestamp | tail -n 80 || true
