name: CI-CD
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

concurrency:
  group: ci-cd-${{ github.ref }}
  cancel-in-progress: true

env:
  K8S_DEPLOYMENT: nestjs-app   # звір із k8s/deployment-app.yaml -> metadata.name
  K8S_CONTAINER: app           # звір із containers[].name

jobs:
  build-push:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_URI: ${{ steps.meta.outputs.image_uri }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (static keys)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Who am I
        run: aws sts get-caller-identity

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # === КРИТИЧНО: контейнерний Buildx і зробити його current ===
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          use: true                  # робить цей builder "current"
          install: true
          driver-opts: |
            image=moby/buildkit:latest
            network=host

      # Прибрати default builder (часто має driver=docker)
      - name: Remove default builder if exists
        run: docker buildx rm default || true

      # Запустити buildkit і перевірити, що driver=docker-container
      - name: Bootstrap & verify builder
        run: |
          docker buildx inspect "${{ steps.buildx.outputs.name }}" --bootstrap
          echo "=== BUILDERS ==="
          docker buildx ls
          echo "=== EXPECTED: current -> docker-container (running) ==="

      - name: Set image tag
        id: vars
        run: echo "TAG=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Build & push image (GHA cache)
        uses: docker/build-push-action@v6
        with:
          builder: ${{ steps.buildx.outputs.name }}   # ← критично: використовуємо саме цей builder
          context: .
          push: true
          tags: |
            ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:${{ steps.vars.outputs.TAG }}
            ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          # Якщо хочеш без кешу, коментуй дві лінії вище
          # або тимчасово:
          # cache-to: type=inline

      - name: Export image URI
        id: meta
        run: echo "image_uri=${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPOSITORY }}:${{ steps.vars.outputs.TAG }}" >> $GITHUB_OUTPUT

  deploy:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (static keys)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Who am I
        run: aws sts get-caller-identity

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.30.0'   # підігнай під версію control plane EKS

      - name: Update kubeconfig for EKS
        run: aws eks update-kubeconfig --name "${{ secrets.EKS_CLUSTER }}" --region "${{ secrets.AWS_REGION }}"

      - name: Ensure namespace + app secrets from ENV_FILE
        run: |
          kubectl apply -f k8s/namespace.yaml || true
          cat > .env <<'EOF'
          ${{ secrets.ENV_FILE }}
          EOF
          kubectl -n "${{ secrets.K8S_NAMESPACE }}" create secret generic app-secrets \
            --from-env-file=.env --dry-run=client -o yaml | kubectl apply -f -

      - name: Apply manifests
        run: |
          kubectl -n "${{ secrets.K8S_NAMESPACE }}" apply -f k8s/deployment-redis.yaml -f k8s/service-redis.yaml
          kubectl -n "${{ secrets.K8S_NAMESPACE }}" apply -f k8s/deployment-app.yaml -f k8s/service-app.yaml
          # опційно:
          # kubectl -n "${{ secrets.K8S_NAMESPACE }}" apply -f k8s/ingress.yaml -f k8s/hpa.yaml -f k8s/networkpolicy.yaml

      - name: Set new image and rollout
        run: |
          kubectl -n "${{ secrets.K8S_NAMESPACE }}" set image deployment/${{ env.K8S_DEPLOYMENT }} ${{ env.K8S_CONTAINER }}="${{ needs.build-push.outputs.IMAGE_URI }}"
          kubectl -n "${{ secrets.K8S_NAMESPACE }}" rollout status deployment/${{ env.K8S_DEPLOYMENT }} --timeout=180s

      # Дебаг після деплою (корисно на налаштуванні)
      - name: Debug resources
        if: always()
        run: |
          kubectl -n "${{ secrets.K8S_NAMESPACE }}" get pods -o wide
          kubectl -n "${{ secrets.K8S_NAMESPACE }}" describe deploy/${{ env.K8S_DEPLOYMENT }} || true
          kubectl -n "${{ secrets.K8S_NAMESPACE }}" logs deploy/${{ env.K8S_DEPLOYMENT }} --tail=120 || true
          kubectl -n "${{ secrets.K8S_NAMESPACE }}" get svc
          kubectl -n "${{ secrets.K8S_NAMESPACE }}" get events --sort-by=.lastTimestamp | tail -n 80 || true
